### ISSUE TITLE
Unable to equip Blahaj Backpack in Trinkets back slot

### ISSUE THREAD

**Issue by Kaylielotl** [RecraftorsMC/blahaj#11]
Just as the title says, I am unable to place the Blahaj Backpack in the Trinkets back slot, despite the fact that the backpacks from Traveler's Backpacks are able to be. This issue is very easily fixable by simply adding "blahaj:blahaj_backpack" to the values in back.json, in \data\trinkets\tags\items\chest\

Another small enough bug that I don't think it warrants an entire issue to itself also relating to the Blahaj Backpack, when the backpack is placed as a block, the block breaking particles from it appear to be missing textures.

Minecraft version: 1.20.1
Fabric version: fabric-loader-0.15.10-1.20.1
Blahaj Expanded version: blahaj_1.20.1-0.6.2
Traveler's Backpacks version: travelersbackpack-fabric-1.20.1-9.1.12
Trinkets version: trinkets-3.7.2

**Comment by NerjalNosk** [comment]
I suppose the integration does not cover the Trinkets compatibility system, will have to be looked into.

Thanks for reporting that issue.

As for the breaking particles, while never mentioned, it is known, it just hasn't really been looked into either. But that only gives ever more reasons to get back onto that integration.

A fix will be worked on soon enough, just please be aware that it will not be before at least 8 days due to irl matters (exam period and alike)

**Comment by Kaylielotl** [comment]
Understood, thank you for letting me know! And good luck on your exams, hope they go well!

**Comment by Kaylielotl** [comment]
I didn't mean to click close, my bad

**Comment by NerjalNosk** [comment]
Fixed in 0.6.3
