### ISSUE TITLE
Backport to 1.18.2?

### ISSUE THREAD

**Issue by rsp4jack** [RecraftorsMC/blahaj#2]

**Comment by NerjalNosk** [comment]
This port has been kept inactive because the original mod has also been as such, since there has been no more need for it to be updated, but also because we have been pretty busy working on another mod that would greatly help further mod porting. We also need to actually ask the mod owner if they are okay with this port even existing. It might at all time just be removed, according to the owner's will.

Then again, the main idea is to port mods to modern versions of Minecraft. While some of us might be interested in backporting, it won't be our main focus unless there really is a high demand for it.
